// Copies the single sources of truth into the app before dev/build:
//   deployments/<NEXT_PUBLIC_CHAIN_ID>.json  (written by contracts/script/Deploy.s.sol)
//   contract ABIs from the Foundry build     (contracts/out)
// No address, chain id or RPC literal lives in component code.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
// Runs before Next.js loads env files, so load them the same way Next does
// (.env.local first, then .env); variables already set in the shell win.
for (const f of ['.env.local', '.env']) {
  if (existsSync(new URL(`../${f}`, import.meta.url))) process.loadEnvFile(new URL(`../${f}`, import.meta.url).pathname)
}
const chainId = process.env.NEXT_PUBLIC_CHAIN_ID
if (!chainId) throw new Error('NEXT_PUBLIC_CHAIN_ID is not set (see apps/web/.env.example)')
const root = new URL('../../../', import.meta.url)
const dep = new URL(`deployments/${chainId}.json`, root)
if (!existsSync(dep)) throw new Error(`deployments/${chainId}.json not found: deploy first (contracts/script/Deploy.s.sol)`)
writeFileSync(new URL('../src/generated/deployment.json', import.meta.url), readFileSync(dep))
const abis = {}
for (const name of ['ScoreRegistry', 'TenorMarket', 'MockPriceOracle', 'MockERC20']) {
  const f = new URL(`contracts/out/${name}.sol/${name}.json`, root)
  if (!existsSync(f)) throw new Error(`${name} ABI missing: run \`forge build\` in contracts/`)
  abis[name] = JSON.parse(readFileSync(f, 'utf8')).abi
}
writeFileSync(new URL('../src/generated/abis.ts', import.meta.url),
  '// GENERATED by scripts/prebuild.mjs from contracts/out. Do not edit.\n' +
  Object.entries(abis).map(([n, a]) => `export const ${n}Abi = ${JSON.stringify(a)} as const\n`).join(''))
console.log(`prebuild: deployment ${chainId}, ABIs ${Object.keys(abis).join(', ')}`)
