// Copies the single sources of truth into the app before dev/build:
//   deployments/<NEXT_PUBLIC_CHAIN_ID>.json  (written by contracts/script/Deploy.s.sol)
//   contract ABIs from the Foundry build     (contracts/out)
// No address, chain id or RPC literal lives in component code.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
// Runs before Next.js loads env files, so load them the same way Next does
// (.env.local first, then .env); variables already set in the shell win.
for (const f of ['.env.local', '.env']) {
  if (existsSync(new URL(`../${f}`, import.meta.url))) process.loadEnvFile(new URL(`../${f}`, import.meta.url).pathname)
}
const chainId = process.env.NEXT_PUBLIC_CHAIN_ID
if (!chainId) throw new Error('NEXT_PUBLIC_CHAIN_ID is not set (see apps/web/.env.example)')
const root = new URL('../../../', import.meta.url)
const dep = new URL(`deployments/${chainId}.json`, root)
if (!existsSync(dep)) throw new Error(`deployments/${chainId}.json not found: deploy first (contracts/script/Deploy.s.sol)`)
writeFileSync(new URL('../src/generated/deployment.json', import.meta.url), readFileSync(dep))
// ABIs: from the Foundry build when present, which also refreshes the
// committed snapshot in apps/web/abis/ (so drift shows up in git diff). Hosts
// without Foundry (Vercel) build from that snapshot.
const abis = {}
mkdirSync(new URL('../abis/', import.meta.url), { recursive: true })
for (const name of ['ScoreRegistry', 'TenorMarket', 'MockPriceOracle', 'MockERC20']) {
  const built = new URL(`contracts/out/${name}.sol/${name}.json`, root)
  const snapshot = new URL(`../abis/${name}.json`, import.meta.url)
  if (existsSync(built)) {
    abis[name] = JSON.parse(readFileSync(built, 'utf8')).abi
    writeFileSync(snapshot, JSON.stringify(abis[name], null, 2) + '\n')
  } else if (existsSync(snapshot)) {
    abis[name] = JSON.parse(readFileSync(snapshot, 'utf8'))
  } else {
    throw new Error(`${name} ABI missing: run \`forge build\` in contracts/`)
  }
}
writeFileSync(new URL('../src/generated/abis.ts', import.meta.url),
  '// GENERATED by scripts/prebuild.mjs from contracts/out. Do not edit.\n' +
  Object.entries(abis).map(([n, a]) => `export const ${n}Abi = ${JSON.stringify(a)} as const\n`).join(''))
console.log(`prebuild: deployment ${chainId}, ABIs ${Object.keys(abis).join(', ')}`)
