// Writes config.yaml from deployments/<CHAIN_ID>.json, the single source of
// contract addresses (written by contracts/script/Deploy.s.sol).
//   CHAIN_ID=10143 node scripts/gen-config.mjs   Monad testnet: HyperSync + RPC fallback
//   CHAIN_ID=31337 RPC_URL=http://127.0.0.1:8545 node scripts/gen-config.mjs   local anvil: RPC only (config.local.yaml)
import { readFileSync, writeFileSync } from 'node:fs'
const chainId = Number(process.env.CHAIN_ID)
if (!chainId) throw new Error('CHAIN_ID not set')
const dep = JSON.parse(readFileSync(new URL(`../../deployments/${chainId}.json`, import.meta.url), 'utf8'))
const rpc = process.env.RPC_URL
if (chainId === 31337 && !rpc) throw new Error('RPC_URL required for a local chain (no HyperSync)')
const rpcBlock = rpc
  ? chainId === 31337
    ? `    rpc:\n      - url: ${rpc}\n        for: sync\n`
    : `    # HyperSync is primary on Monad testnet; RPC takes over if it is unavailable.\n    rpc:\n      - url: ${rpc}\n        for: fallback\n`
  : ''
const yaml = `# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
# GENERATED by scripts/gen-config.mjs from deployments/${chainId}.json. Do not edit.
name: tenor-indexer
description: Tenor history and aggregates (current state is read from chain)
# Transaction hashes for explorer links and for joining BadDebtRealized to the
# Liquidated event that follows it in the same transaction.
field_selection:
  transaction_fields:
    - hash
contracts:
  - name: ScoreRegistry
    abi_file_path: ./abis/ScoreRegistry.json
    events:
      - event: AttestationSubmitted
      - event: LiquidationRecorded
  - name: TenorMarket
    abi_file_path: ./abis/TenorMarket.json
    events:
      - event: Deposit
      - event: Withdraw
      - event: CollateralDeposited
      - event: CollateralWithdrawn
      - event: Retiered
      - event: Borrowed
      - event: Repaid
      - event: Liquidated
      - event: BadDebtRealized
      - event: InterestAccrued
chains:
  - id: ${chainId}
    start_block: ${dep.startBlock}
${rpcBlock}    contracts:
      - name: ScoreRegistry
        address: "${dep.scoreRegistry}"
      - name: TenorMarket
        address: "${dep.tenorMarket}"
`
// config.yaml is the committed testnet config (Envio Cloud's default path).
// A local chain gets config.local.yaml (gitignored); run it with
// ENVIO_CONFIG=config.local.yaml.
const out = chainId === 31337 ? 'config.local.yaml' : 'config.yaml'
writeFileSync(new URL(`../${out}`, import.meta.url), yaml)
console.log(`${out} for chain ${chainId}, start block ${dep.startBlock}`)
